// Sample of TOP 500
const ratingGrossMovieData = [
  { rating: 93, gross: 2834, title: "The Shawshank Redemption" },
  { rating: 92, gross: 13497, title: "The Godfather" },
  { rating: 90, gross: 573, title: "The Godfather: Part II" },
  { rating: 89, gross: 969, title: "Schindler's List" },
  { rating: 89, gross: 10793, title: "Pulp Fiction" },
  { rating: 89, gross: 377, title: "12 Angry Men" },
  { rating: 88, gross: 33025, title: "Forrest Gump" },
  { rating: 88, gross: 29048, title: "Star Wars: Episode V" },
  { rating: 88, gross: 4684, title: "Goodfellas" },
  { rating: 87, gross: 1120, title: "One Flew Over the Cuckoo's Nest" },
  { rating: 87, gross: 4635, title: "Seven Samurai" },
  { rating: 86, gross: 32274, title: "Star Wars: Episode IV" },
  { rating: 86, gross: 13074, title: "The Silence of the Lambs" },
  { rating: 86, gross: 21654, title: "Saving Private Ryan" },
  { rating: 86, gross: 10013, title: "Se7en" },
  { rating: 85, gross: 20484, title: "Terminator 2: Judgment Day" },
  { rating: 85, gross: 42278, title: "The Lion King" },
  { rating: 85, gross: 2334, title: "The Usual Suspects" },
  { rating: 85, gross: 320, title: "Psycho" },
  { rating: 85, gross: 102, title: "Casablanca" },
  { rating: 78, gross: 65933, title: "Titanic" },
  { rating: 81, gross: 165, title: "Trainspotting" },
  { rating: 83, gross: 159, title: "Citizen Kane" },
  { rating: 81, gross: 3287, title: "Blade Runner" },
  {
    rating: 84,
    gross: 24816,
    title: "Indiana Jones and the Raiders of the Lost Ark",
  },
  { rating: 76, gross: 93666, title: "Star Wars: Ep VII - Force Awakens" },
  { rating: 80, gross: 62330, title: "The Avengers" },
  { rating: 79, gross: 76050, title: "Avatar" },
];

const averageRatingRuntimeMovieData = [
  {
    runTime: 16,
    averageRating: 7.7,
  },
  {
    runTime: 24,
    averageRating: 7.8,
  },
  {
    runTime: 25,
    averageRating: 8.4,
  },
  {
    runTime: 26,
    averageRating: 8.4,
  },
  {
    runTime: 30,
    averageRating: 8.2,
  },
  {
    runTime: 45,
    averageRating: 8.200000000000001,
  },
  {
    runTime: 66,
    averageRating: 8.0,
  },
  {
    runTime: 67,
    averageRating: 8.099999999999996,
  },
  {
    runTime: 68,
    averageRating: 8.299999999999999,
  },
  {
    runTime: 69,
    averageRating: 7.799999999999998,
  },
  {
    runTime: 70,
    averageRating: 7.8,
  },
  {
    runTime: 73,
    averageRating: 7.3,
  },
  {
    runTime: 74,
    averageRating: 8.1,
  },
  {
    runTime: 75,
    averageRating: 7.866666666666666,
  },
  {
    runTime: 76,
    averageRating: 8.0,
  },
  {
    runTime: 78,
    averageRating: 7.6,
  },
  {
    runTime: 80,
    averageRating: 7.928,
  },
  {
    runTime: 81,
    averageRating: 8.231034482758625,
  },
  {
    runTime: 82,
    averageRating: 7.9,
  },
  {
    runTime: 83,
    averageRating: 7.857142857142854,
  },
  {
    runTime: 84,
    averageRating: 7.902941176470588,
  },
  {
    runTime: 85,
    averageRating: 7.9714285714285715,
  },
  {
    runTime: 86,
    averageRating: 7.996969696969693,
  },
  {
    runTime: 87,
    averageRating: 8.450000000000001,
  },
  {
    runTime: 88,
    averageRating: 8.278749999999997,
  },
  {
    runTime: 89,
    averageRating: 8.206097560975609,
  },
  {
    runTime: 90,
    averageRating: 7.989361702127663,
  },
  {
    runTime: 91,
    averageRating: 8.053846153846156,
  },
  {
    runTime: 92,
    averageRating: 8.083333333333334,
  },
  {
    runTime: 93,
    averageRating: 8.01639344262295,
  },
  {
    runTime: 94,
    averageRating: 8.015151515151512,
  },
  {
    runTime: 95,
    averageRating: 8.106896551724135,
  },
  {
    runTime: 96,
    averageRating: 8.16333333333333,
  },
  {
    runTime: 97,
    averageRating: 8.026190476190473,
  },
  {
    runTime: 98,
    averageRating: 8.140425531914894,
  },
  {
    runTime: 99,
    averageRating: 8.048780487804876,
  },
  {
    runTime: 100,
    averageRating: 8.051063829787232,
  },
  {
    runTime: 101,
    averageRating: 8.104166666666664,
  },
  {
    runTime: 102,
    averageRating: 8.11304347826087,
  },
  {
    runTime: 103,
    averageRating: 8.127450980392158,
  },
  {
    runTime: 104,
    averageRating: 8.093478260869566,
  },
  {
    runTime: 105,
    averageRating: 8.083783783783784,
  },
  {
    runTime: 106,
    averageRating: 8.122500000000002,
  },
  {
    runTime: 107,
    averageRating: 8.132692307692305,
  },
  {
    runTime: 108,
    averageRating: 8.11063829787234,
  },
  {
    runTime: 109,
    averageRating: 8.167346938775512,
  },
  {
    runTime: 110,
    averageRating: 8.103030303030305,
  },
  {
    runTime: 111,
    averageRating: 8.086206896551722,
  },
  {
    runTime: 112,
    averageRating: 8.212500000000002,
  },
  {
    runTime: 113,
    averageRating: 8.223809523809521,
  },
  {
    runTime: 114,
    averageRating: 8.137931034482758,
  },
  {
    runTime: 115,
    averageRating: 8.156097560975608,
  },
  {
    runTime: 116,
    averageRating: 8.236666666666666,
  },
  {
    runTime: 117,
    averageRating: 8.138709677419353,
  },
  {
    runTime: 118,
    averageRating: 8.167857142857143,
  },
  {
    runTime: 119,
    averageRating: 8.138461538461537,
  },
  {
    runTime: 120,
    averageRating: 8.108695652173911,
  },
  {
    runTime: 121,
    averageRating: 8.243478260869566,
  },
  {
    runTime: 122,
    averageRating: 8.169230769230768,
  },
  {
    runTime: 123,
    averageRating: 8.125925925925925,
  },
  {
    runTime: 124,
    averageRating: 8.194736842105263,
  },
  {
    runTime: 125,
    averageRating: 8.14090909090909,
  },
  {
    runTime: 126,
    averageRating: 8.166666666666666,
  },
  {
    runTime: 127,
    averageRating: 8.157692307692306,
  },
  {
    runTime: 128,
    averageRating: 8.170588235294122,
  },
  {
    runTime: 129,
    averageRating: 8.119337016574587,
  },
  {
    runTime: 130,
    averageRating: 8.249444444444444,
  },
  {
    runTime: 131,
    averageRating: 8.147826086956526,
  },
  {
    runTime: 132,
    averageRating: 8.131683168316846,
  },
  {
    runTime: 133,
    averageRating: 8.34754098360656,
  },
  {
    runTime: 134,
    averageRating: 8.1140625,
  },
  {
    runTime: 135,
    averageRating: 7.959574468085105,
  },
  {
    runTime: 136,
    averageRating: 8.331182795698924,
  },
  {
    runTime: 137,
    averageRating: 8.217,
  },
  {
    runTime: 138,
    averageRating: 8.057377049180339,
  },
  {
    runTime: 139,
    averageRating: 8.40243902439025,
  },
  {
    runTime: 140,
    averageRating: 8.082352941176467,
  },
  {
    runTime: 141,
    averageRating: 7.944,
  },
  {
    runTime: 142,
    averageRating: 8.925806451612907,
  },
  {
    runTime: 143,
    averageRating: 8.153658536585368,
  },
  {
    runTime: 144,
    averageRating: 8.204545454545453,
  },
  {
    runTime: 145,
    averageRating: 8.125925925925925,
  },
  {
    runTime: 146,
    averageRating: 8.238461538461537,
  },
  {
    runTime: 147,
    averageRating: 8.123529411764706,
  },
  {
    runTime: 148,
    averageRating: 8.261538461538462,
  },
  {
    runTime: 149,
    averageRating: 8.163636363636362,
  },
  {
    runTime: 150,
    averageRating: 8.136842105263158,
  },
  {
    runTime: 151,
    averageRating: 8.257142857142856,
  },
  {
    runTime: 152,
    averageRating: 8.283333333333333,
  },
  {
    runTime: 153,
    averageRating: 8.270588235294119,
  },
  {
    runTime: 154,
    averageRating: 8.283333333333333,
  },
  {
    runTime: 155,
    averageRating: 8.138095238095237,
  },
  {
    runTime: 156,
    averageRating: 8.2,
  },
  {
    runTime: 157,
    averageRating: 8.2,
  },
  {
    runTime: 158,
    averageRating: 8.15,
  },
  {
    runTime: 159,
    averageRating: 8.075,
  },
  {
    runTime: 160,
    averageRating: 8.083333333333332,
  },
  {
    runTime: 161,
    averageRating: 8.300000000000002,
  },
  {
    runTime: 162,
    averageRating: 8.077777777777776,
  },
  {
    runTime: 163,
    averageRating: 8.0,
  },
  {
    runTime: 164,
    averageRating: 8.425,
  },
  {
    runTime: 165,
    averageRating: 8.3375,
  },
  {
    runTime: 166,
    averageRating: 8.0,
  },
  {
    runTime: 167,
    averageRating: 8.0,
  },
  {
    runTime: 168,
    averageRating: 8.2,
  },
  {
    runTime: 169,
    averageRating: 8.171428571428573,
  },
  {
    runTime: 170,
    averageRating: 8.137500000000001,
  },
  {
    runTime: 171,
    averageRating: 8.3,
  },
  {
    runTime: 172,
    averageRating: 7.9,
  },
  {
    runTime: 174,
    averageRating: 8.1,
  },
  {
    runTime: 175,
    averageRating: 8.4,
  },
  {
    runTime: 177,
    averageRating: 8.2,
  },
  {
    runTime: 178,
    averageRating: 8.420000000000002,
  },
  {
    runTime: 179,
    averageRating: 8.299999999999999,
  },
  {
    runTime: 180,
    averageRating: 8.2,
  },
  {
    runTime: 181,
    averageRating: 8.1,
  },
  {
    runTime: 183,
    averageRating: 8.1,
  },
  {
    runTime: 185,
    averageRating: 8.0,
  },
  {
    runTime: 188,
    averageRating: 8.15,
  },
  {
    runTime: 189,
    averageRating: 8.6,
  },
  {
    runTime: 191,
    averageRating: 8.2,
  },
  {
    runTime: 193,
    averageRating: 8.0,
  },
  {
    runTime: 194,
    averageRating: 7.8,
  },
  {
    runTime: 195,
    averageRating: 8.9,
  },
  {
    runTime: 196,
    averageRating: 8.6,
  },
  {
    runTime: 197,
    averageRating: 8.0,
  },
  {
    runTime: 201,
    averageRating: 9.0,
  },
  {
    runTime: 202,
    averageRating: 8.7,
  },
  {
    runTime: 205,
    averageRating: 8.0,
  },
  {
    runTime: 207,
    averageRating: 8.5,
  },
  {
    runTime: 209,
    averageRating: 7.8,
  },
  {
    runTime: 212,
    averageRating: 8.0,
  },
  {
    runTime: 220,
    averageRating: 7.9,
  },
  {
    runTime: 224,
    averageRating: 8.1,
  },
  {
    runTime: 228,
    averageRating: 8.300000000000002,
  },
  {
    runTime: 229,
    averageRating: 8.300000000000002,
  },
  {
    runTime: 238,
    averageRating: 8.099999999999996,
  },
  {
    runTime: 242,
    averageRating: 7.7,
  },
  {
    runTime: 321,
    averageRating: 8.2,
  },
];

const directorsAvgRatingData = [
  { moviesCount: 154, ratingAvg: 8.33, title: "Steven Spielberg" },
  { moviesCount: 199, ratingAvg: 8.27, title: "Stanley Kubrick" },
  { moviesCount: 154, ratingAvg: 8.33, title: "Steven Spielberg" },
  { moviesCount: 145, ratingAvg: 8.27, title: "Billy Wilder" },
  { moviesCount: 131, ratingAvg: 8.33, title: "Martin Scorsese" },
  { moviesCount: 130, ratingAvg: 8.3, title: "Akira Kurosawa" },
  { moviesCount: 116, ratingAvg: 8.39, title: "Charles Chaplin" },
  { moviesCount: 101, ratingAvg: 8.4, title: "Quentin Tarantino" },
  { moviesCount: 99, ratingAvg: 8.45, title: "Sergio Leone" },
  { moviesCount: 99, ratingAvg: 8.53, title: "Christopher Nolan" },
  { moviesCount: 91, ratingAvg: 8.71, title: "Francis Ford Coppola" },
  { moviesCount: 90, ratingAvg: 8.23, title: "Frank Capra" },
  { moviesCount: 88, ratingAvg: 8.31, title: "Hayao Miyazaki" },
  { moviesCount: 81, ratingAvg: 8.24, title: "James Cameron" },
  { moviesCount: 76, ratingAvg: 8.31, title: "Ridley Scott" },
  { moviesCount: 75, ratingAvg: 8.17, title: "Ingmar Bergman" },
  { moviesCount: 72, ratingAvg: 8.09, title: "Clint Eastwood" },
  { moviesCount: 71, ratingAvg: 8.01, title: "John Huston" },
  { moviesCount: 69, ratingAvg: 8.41, title: "Sidney Lumet" },
  { moviesCount: 68, ratingAvg: 8.63, title: "Peter Jackson" },
  { moviesCount: 66, ratingAvg: 8.04, title: "Rob Reiner" },
  { moviesCount: 65, ratingAvg: 7.97, title: "Joel Coen" },
  { moviesCount: 63, ratingAvg: 8.16, title: "David Lean" },
  { moviesCount: 63, ratingAvg: 8.07, title: "William Wyler" },
  { moviesCount: 61, ratingAvg: 8.55, title: "David Fincher" },
  { moviesCount: 59, ratingAvg: 8.07, title: "Terry Gilliam" },
  { moviesCount: 59, ratingAvg: 8, title: "John Ford" },
  { moviesCount: 54, ratingAvg: 8.46, title: "Milos Forman" },
  { moviesCount: 54, ratingAvg: 8.61, title: "Robert Zemeckis" },
  { moviesCount: 53, ratingAvg: 8.28, title: "Roman Polanski" },
  { moviesCount: 52, ratingAvg: 8.02, title: "Federico Fellini" },
  { moviesCount: 51, ratingAvg: 8.3, title: "Fritz Lang" },
  { moviesCount: 51, ratingAvg: 7.91, title: "Howard Hawks" },
  { moviesCount: 49, ratingAvg: 8.97, title: "Frank Darabont" },
  { moviesCount: 49, ratingAvg: 8.05, title: "Victor Fleming" },
  { moviesCount: 49, ratingAvg: 8.16, title: "George Roy Hill" },
  { moviesCount: 48, ratingAvg: 8.16, title: "Orson Welles" },
  { moviesCount: 45, ratingAvg: 7.95, title: "Woody Allen" },
  { moviesCount: 44, ratingAvg: 8.2, title: "Guy Ritchie" },
  { moviesCount: 41, ratingAvg: 8.06, title: "Elia Kazan" },
  { moviesCount: 40, ratingAvg: 8.04, title: "David Lynch" },
  { moviesCount: 39, ratingAvg: 8.13, title: "Pete Docter" },
  { moviesCount: 38, ratingAvg: 8.31, title: "Michael Curtiz" },
  { moviesCount: 37, ratingAvg: 8.16, title: "John Lasseter" },
  { moviesCount: 35, ratingAvg: 8.2, title: "Stanley Donen" },
  { moviesCount: 35, ratingAvg: 8, title: "Mike Nichols" },
  { moviesCount: 34, ratingAvg: 8.04, title: "Danny Boyle" },
  { moviesCount: 33, ratingAvg: 8.15, title: "Joseph L. Mankiewicz" },
  { moviesCount: 33, ratingAvg: 8.23, title: "Andrew Stanton" },
  { moviesCount: 32, ratingAvg: 8.26, title: "Mel Gibson" },
  { moviesCount: 32, ratingAvg: 8.31, title: "Luc Besson" },
  { moviesCount: 32, ratingAvg: 8.1, title: "Michael Mann" },
  { moviesCount: 31, ratingAvg: 8.2, title: "Darren Aronofsky" },
  { moviesCount: 29, ratingAvg: 8.42, title: "Bryan Singer" },
  { moviesCount: 28, ratingAvg: 8.52, title: "George Lucas" },
  { moviesCount: 28, ratingAvg: 8.04, title: "Ron Howard" },
  { moviesCount: 28, ratingAvg: 8.03, title: "Peter Weir" },
  { moviesCount: 28, ratingAvg: 7.95, title: "Franklin J. Schaffner" },
  { moviesCount: 28, ratingAvg: 8.16, title: "John McTiernan" },
  { moviesCount: 28, ratingAvg: 8.09, title: "Oliver Stone" },
  { moviesCount: 28, ratingAvg: 8.08, title: "Paul Thomas Anderson" },
  { moviesCount: 28, ratingAvg: 8.1, title: "Henri-Georges Clouzot" },
  { moviesCount: 27, ratingAvg: 8.18, title: "John Sturges" },
  { moviesCount: 27, ratingAvg: 8.26, title: "Sam Mendes" },
  { moviesCount: 26, ratingAvg: 8.7, title: "Irvin Kershner" },
  { moviesCount: 26, ratingAvg: 8.2, title: "Robert Mulligan" },
  { moviesCount: 26, ratingAvg: 8.3, title: "Richard Marquand" },
  { moviesCount: 26, ratingAvg: 8.5, title: "Giuseppe Tornatore" },
  { moviesCount: 26, ratingAvg: 8.6, title: "Jonathan Demme" },
  { moviesCount: 26, ratingAvg: 8.1, title: "Carol Reed" },
  { moviesCount: 26, ratingAvg: 8.3, title: "Wolfgang Petersen" },
  { moviesCount: 26, ratingAvg: 8.1, title: "Terry Jones" },
  { moviesCount: 26, ratingAvg: 8.1, title: "Michael Cimino" },
  { moviesCount: 26, ratingAvg: 8.1, title: "Stuart Rosenberg" },
  { moviesCount: 26, ratingAvg: 8.16, title: "Brian De Palma" },
  { moviesCount: 25, ratingAvg: 8.59, title: "Lana Wachowski" },
  { moviesCount: 25, ratingAvg: 7.94, title: "Richard Attenborough" },
  { moviesCount: 25, ratingAvg: 8.2, title: "Curtis Hanson" },
  { moviesCount: 25, ratingAvg: 8.29, title: "Vittorio De Sica" },
  { moviesCount: 24, ratingAvg: 7.94, title: "Fred Zinnemann" },
  { moviesCount: 24, ratingAvg: 7.85, title: "Tim Burton" },
  { moviesCount: 23, ratingAvg: 8, title: "Krzysztof Kieslowski" },
  { moviesCount: 23, ratingAvg: 8.1, title: "M. Night Shyamalan" },
  { moviesCount: 23, ratingAvg: 8.6, title: "Roberto Benigni" },
  { moviesCount: 23, ratingAvg: 8.5, title: "Tony Kaye" },
  { moviesCount: 23, ratingAvg: 8.1, title: "Clyde Bruckman" },
  { moviesCount: 23, ratingAvg: 8.06, title: "Alejandro G. IÃ±Ã¡rritu" },
  { moviesCount: 23, ratingAvg: 8.33, title: "Park Chan-wook" },
  { moviesCount: 22, ratingAvg: 8.06, title: "Richard Linklater" },
  { moviesCount: 22, ratingAvg: 7.87, title: "George Cukor" },
  { moviesCount: 22, ratingAvg: 8, title: "Harold Ramis" },
  { moviesCount: 22, ratingAvg: 8.1, title: "FranÃ§ois Truffaut" },
  { moviesCount: 22, ratingAvg: 7.99, title: "F.W. Murnau" },
  { moviesCount: 21, ratingAvg: 8.3, title: "Jean-Pierre Jeunet" },
  { moviesCount: 21, ratingAvg: 8.17, title: "Denis Villeneuve" },
  { moviesCount: 20, ratingAvg: 8.26, title: "Gus Van Sant" },
  { moviesCount: 20, ratingAvg: 8.19, title: "Thomas Vinterberg" },
  { moviesCount: 19, ratingAvg: 8.09, title: "Andrei Tarkovsky" },
  { moviesCount: 19, ratingAvg: 8.6, title: "Fernando Meirelles" },
  { moviesCount: 19, ratingAvg: 8.5, title: "Isao Takahata" },
  { moviesCount: 18, ratingAvg: 7.74, title: "Robert Wise" },
  { moviesCount: 18, ratingAvg: 7.9, title: "John Frankenheimer" },
  { moviesCount: 18, ratingAvg: 8, title: "Brad Bird" },
  { moviesCount: 18, ratingAvg: 8.3, title: "Michel Gondry" },
  { moviesCount: 17, ratingAvg: 7.74, title: "Edward Zwick" },
  { moviesCount: 17, ratingAvg: 8.5, title: "Roger Allers" },
  { moviesCount: 17, ratingAvg: 7.9, title: "Sam Peckinpah" },
  { moviesCount: 17, ratingAvg: 7.96, title: "William Friedkin" },
  { moviesCount: 17, ratingAvg: 8, title: "Charles Laughton" },
  { moviesCount: 17, ratingAvg: 8.19, title: "Stanley Kramer" },
  { moviesCount: 17, ratingAvg: 8, title: "Richard Kelly" },
  { moviesCount: 17, ratingAvg: 8.1, title: "Terry George" },
  { moviesCount: 17, ratingAvg: 8.2, title: "Oliver Hirschbiegel" },
  { moviesCount: 17, ratingAvg: 8.1, title: "John Carpenter" },
  { moviesCount: 17, ratingAvg: 8.26, title: "Lee Unkrich" },
  { moviesCount: 16, ratingAvg: 7.77, title: "Ang Lee" },
  { moviesCount: 16, ratingAvg: 8.04, title: "Jim Sheridan" },
  { moviesCount: 16, ratingAvg: 8, title: "Robert Rossen" },
  { moviesCount: 16, ratingAvg: 8, title: "Otto Preminger" },
  { moviesCount: 16, ratingAvg: 8.1, title: "James McTeigue" },
  { moviesCount: 16, ratingAvg: 8.2, title: "Guillermo del Toro" },
  { moviesCount: 16, ratingAvg: 8.07, title: "Ethan Coen" },
  { moviesCount: 15, ratingAvg: 7.8, title: "Leo McCarey" },
  { moviesCount: 15, ratingAvg: 7.93, title: "Mel Brooks" },
  { moviesCount: 15, ratingAvg: 7.9, title: "Bob Clark" },
  {
    moviesCount: 15,
    ratingAvg: 8.4,
    title: "Florian Henckel von Donnersmarck",
  },
  { moviesCount: 15, ratingAvg: 8.3, title: "Rajkumar Hirani" },
  { moviesCount: 14, ratingAvg: 7.5, title: "Kenneth Branagh" },
  { moviesCount: 14, ratingAvg: 7.96, title: "Hal Ashby" },
  { moviesCount: 14, ratingAvg: 7.93, title: "Gary Trousdale" },
  { moviesCount: 14, ratingAvg: 7.94, title: "Lasse HallstrÃ¶m" },
  { moviesCount: 14, ratingAvg: 7.46, title: "Robert Altman" },
  { moviesCount: 14, ratingAvg: 7.77, title: "Arthur Penn" },
  { moviesCount: 14, ratingAvg: 8.1, title: "Lewis Milestone" },
  { moviesCount: 14, ratingAvg: 8.1, title: "Sean Penn" },
  { moviesCount: 14, ratingAvg: 8.1, title: "John G. Avildsen" },
  { moviesCount: 13, ratingAvg: 8.11, title: "Nick Park" },
  { moviesCount: 13, ratingAvg: 7.96, title: "Wim Wenders" },
  { moviesCount: 13, ratingAvg: 7.9, title: "Henry Koster" },
  { moviesCount: 13, ratingAvg: 8, title: "Gore Verbinski" },
  { moviesCount: 12, ratingAvg: 7.53, title: "Kevin Smith" },
  { moviesCount: 12, ratingAvg: 7.75, title: "John Woo" },
  { moviesCount: 12, ratingAvg: 8, title: "Frank Miller" },
  { moviesCount: 12, ratingAvg: 8.1, title: "Gillo Pontecorvo" },
  { moviesCount: 12, ratingAvg: 8.1, title: "Mathieu Kassovitz" },
  { moviesCount: 12, ratingAvg: 7.97, title: "Paul Greengrass" },
  { moviesCount: 12, ratingAvg: 8.1, title: "Dean DeBlois" },
  { moviesCount: 12, ratingAvg: 8.2, title: "Juan JosÃ© Campanella" },
  { moviesCount: 12, ratingAvg: 8.1, title: "Adam Elliot" },
  { moviesCount: 12, ratingAvg: 8.23, title: "Bong Joon Ho" },
  { moviesCount: 11, ratingAvg: 7.96, title: "Barry Levinson" },
  { moviesCount: 11, ratingAvg: 7.9, title: "Merian C. Cooper" },
  { moviesCount: 11, ratingAvg: 8.1, title: "Carl Theodor Dreyer" },
  { moviesCount: 11, ratingAvg: 8.3, title: "Asghar Farhadi" },
  { moviesCount: 11, ratingAvg: 8.1, title: "Gavin O'Connor" },
  { moviesCount: 11, ratingAvg: 8.1, title: "David Yates" },
  { moviesCount: 10, ratingAvg: 7.75, title: "Philip Kaufman" },
  { moviesCount: 10, ratingAvg: 8, title: "Billy Bob Thornton" },
  { moviesCount: 10, ratingAvg: 8, title: "Alan J. Pakula" },
  { moviesCount: 10, ratingAvg: 7.8, title: "James Whale" },
  { moviesCount: 10, ratingAvg: 8.1, title: "Kar-Wai Wong" },
  { moviesCount: 10, ratingAvg: 8.03, title: "James Mangold" },
  { moviesCount: 10, ratingAvg: 8, title: "Andrew Lau" },
  { moviesCount: 10, ratingAvg: 8.5, title: "Olivier Nakache" },
  { moviesCount: 9, ratingAvg: 7.63, title: "James Ivory" },
  { moviesCount: 9, ratingAvg: 7.99, title: "Yimou Zhang" },
  { moviesCount: 9, ratingAvg: 7.7, title: "Spike Jonze" },
  { moviesCount: 9, ratingAvg: 7.7, title: "Tom Tykwer" },
  { moviesCount: 9, ratingAvg: 7.9, title: "Pedro AlmodÃ³var" },
  { moviesCount: 9, ratingAvg: 7.9, title: "Norman Jewison" },
  { moviesCount: 9, ratingAvg: 8, title: "Robert Hamer" },
  { moviesCount: 9, ratingAvg: 8.4, title: "Aamir Khan" },
  { moviesCount: 8, ratingAvg: 8, title: "Claude Berri" },
  { moviesCount: 8, ratingAvg: 7.7, title: "James Algar" },
  { moviesCount: 8, ratingAvg: 7.75, title: "Cameron Crowe" },
  { moviesCount: 8, ratingAvg: 8, title: "Sergei M. Eisenstein" },
  { moviesCount: 8, ratingAvg: 8.3, title: "Elem Klimov" },
  { moviesCount: 8, ratingAvg: 8, title: "Martin McDonagh" },
  { moviesCount: 8, ratingAvg: 8, title: "Tate Taylor" },
  { moviesCount: 8, ratingAvg: 8.1, title: "Steve McQueen" },
  { moviesCount: 8, ratingAvg: 8.1, title: "Wes Anderson" },
  { moviesCount: 8, ratingAvg: 8.44, title: "Damien Chazelle" },
  { moviesCount: 7, ratingAvg: 7.94, title: "Mike Leigh" },
  { moviesCount: 7, ratingAvg: 7.44, title: "Atom Egoyan" },
  { moviesCount: 7, ratingAvg: 7.8, title: "Roland JoffÃ©" },
  { moviesCount: 7, ratingAvg: 7.6, title: "William Cottrell" },
  { moviesCount: 7, ratingAvg: 7.8, title: "John Schlesinger" },
  { moviesCount: 7, ratingAvg: 8.1, title: "Jean Renoir" },
  { moviesCount: 7, ratingAvg: 7.9, title: "Sam Wood" },
  { moviesCount: 7, ratingAvg: 7.8, title: "Alfonso CuarÃ³n" },
  { moviesCount: 7, ratingAvg: 8.03, title: "Tom McCarthy" },
  { moviesCount: 7, ratingAvg: 7.87, title: "J.J. Abrams" },
  { moviesCount: 7, ratingAvg: 8.2, title: "YasujirÃ´ Ozu" },
  { moviesCount: 7, ratingAvg: 8.1, title: "Rakeysh Omprakash Mehra" },
  { moviesCount: 7, ratingAvg: 8.1, title: "George Miller" },
  { moviesCount: 7, ratingAvg: 8.1, title: "DamiÃ¡n Szifron" },
  { moviesCount: 7, ratingAvg: 8.4, title: "Anthony Russo" },
  { moviesCount: 6, ratingAvg: 7.8, title: "Andrew Davis" },
  { moviesCount: 6, ratingAvg: 7.7, title: "John Boorman" },
  { moviesCount: 6, ratingAvg: 7.9, title: "Anthony Harvey" },
  { moviesCount: 6, ratingAvg: 7.9, title: "Andrew Adamson" },
  { moviesCount: 6, ratingAvg: 7.7, title: "Paul Haggis" },
  { moviesCount: 6, ratingAvg: 8, title: "Julian Schnabel" },
  { moviesCount: 6, ratingAvg: 8.2, title: "Buster Keaton" },
  { moviesCount: 6, ratingAvg: 8, title: "Wilson Yip" },
  { moviesCount: 6, ratingAvg: 8.2, title: "Cagan Irmak" },
  { moviesCount: 6, ratingAvg: 8.3, title: "Majid Majidi" },
  { moviesCount: 6, ratingAvg: 8.1, title: "Lenny Abrahamson" },
  { moviesCount: 6, ratingAvg: 8.2, title: "Yavuz Turgul" },
  { moviesCount: 5, ratingAvg: 7.56, title: "Marc Caro" },
  { moviesCount: 5, ratingAvg: 7.5, title: "Tim Robbins" },
  { moviesCount: 5, ratingAvg: 8.1, title: "Emir Kusturica" },
  { moviesCount: 5, ratingAvg: 7.58, title: "Sam Raimi" },
  { moviesCount: 5, ratingAvg: 7.92, title: "Lars von Trier" },
  { moviesCount: 5, ratingAvg: 8, title: "W.S. Van Dyke" },
  { moviesCount: 5, ratingAvg: 8.2, title: "Ernst Lubitsch" },
  { moviesCount: 5, ratingAvg: 8.6, title: "Masaki Kobayashi" },
  { moviesCount: 5, ratingAvg: 7.9, title: "Tomas Alfredson" },
  { moviesCount: 5, ratingAvg: 8, title: "Tom Hooper" },
  { moviesCount: 5, ratingAvg: 8.2, title: "Anurag Kashyap" },
  { moviesCount: 5, ratingAvg: 8.4, title: "Nitesh Tiwari" },
  { moviesCount: 5, ratingAvg: 8.4, title: "Makoto Shinkai" },
  { moviesCount: 4, ratingAvg: 7.28, title: "Baz Luhrmann" },
  { moviesCount: 4, ratingAvg: 7.8, title: "John Landis" },
  { moviesCount: 4, ratingAvg: 7.68, title: "Jim Jarmusch" },
  { moviesCount: 4, ratingAvg: 8, title: "Katsuhiro Ã”tomo" },
  { moviesCount: 4, ratingAvg: 8, title: "Ron Clements" },
  { moviesCount: 4, ratingAvg: 7.7, title: "Nicholas Ray" },
  { moviesCount: 4, ratingAvg: 7.5, title: "Charles Crichton" },
  { moviesCount: 4, ratingAvg: 7.55, title: "Stephen Frears" },
  { moviesCount: 4, ratingAvg: 7.7, title: "James L. Brooks" },
  { moviesCount: 4, ratingAvg: 7.45, title: "Steven Soderbergh" },
  { moviesCount: 4, ratingAvg: 8, title: "Walter Salles" },
  { moviesCount: 4, ratingAvg: 7.7, title: "Alejandro AmenÃ¡bar" },
  { moviesCount: 4, ratingAvg: 7.9, title: "Jean Cocteau" },
  { moviesCount: 4, ratingAvg: 7.8, title: "Jonathan Dayton" },
  { moviesCount: 4, ratingAvg: 7.9, title: "Neill Blomkamp" },
  { moviesCount: 4, ratingAvg: 8, title: "Joss Whedon" },
  { moviesCount: 4, ratingAvg: 8.13, title: "Ashutosh Gowariker" },
  { moviesCount: 4, ratingAvg: 8, title: "James Gunn" },
  { moviesCount: 4, ratingAvg: 8.2, title: "Nishikant Kamat" },
  { moviesCount: 4, ratingAvg: 8.4, title: "Bob Persichetti" },
  { moviesCount: 3, ratingAvg: 7.4, title: "John Sayles" },
  { moviesCount: 3, ratingAvg: 7.7, title: "Michael Radford" },
  { moviesCount: 3, ratingAvg: 7.9, title: "Lee Tamahori" },
  { moviesCount: 3, ratingAvg: 7.4, title: "Wayne Wang" },
  { moviesCount: 3, ratingAvg: 7.6, title: "Blake Edwards" },
  { moviesCount: 3, ratingAvg: 7.9, title: "Tony Scott" },
  { moviesCount: 3, ratingAvg: 7.5, title: "Jean-Paul Rappeneau" },
  { moviesCount: 3, ratingAvg: 7.7, title: "Jon Avnet" },
  { moviesCount: 3, ratingAvg: 7.5, title: "Phil Alden Robinson" },
  { moviesCount: 3, ratingAvg: 7.2, title: "Doug Liman" },
  { moviesCount: 3, ratingAvg: 7.5, title: "Jerome Robbins" },
  { moviesCount: 3, ratingAvg: 7.7, title: "Guy Hamilton" },
  { moviesCount: 3, ratingAvg: 7.1, title: "John Madden" },
  { moviesCount: 3, ratingAvg: 7.8, title: "Joe Johnston" },
  { moviesCount: 3, ratingAvg: 7.7, title: "Sofia Coppola" },
  { moviesCount: 3, ratingAvg: 7.6, title: "Marc Forster" },
  { moviesCount: 3, ratingAvg: 8.1, title: "Robert Wiene" },
  { moviesCount: 3, ratingAvg: 8.1, title: "Jules Dassin" },
  { moviesCount: 3, ratingAvg: 8, title: "William A. Wellman" },
  { moviesCount: 3, ratingAvg: 8, title: "Kim Ki-duk" },
  { moviesCount: 3, ratingAvg: 8.4, title: "Todd Phillips" },
  { moviesCount: 3, ratingAvg: 8.4, title: "Nadine Labaki" },
  { moviesCount: 3, ratingAvg: 8.2, title: "Peter Farrelly" },
  { moviesCount: 3, ratingAvg: 8.2, title: "Sriram Raghavan" },
  { moviesCount: 3, ratingAvg: 8.2, title: "Sergio Pablos" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Anthony Minghella" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Michael Bay" },
  { moviesCount: 2, ratingAvg: 6.8, title: "Chris Noonan" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Joel Schumacher" },
  { moviesCount: 2, ratingAvg: 6.95, title: "Allan Moyle" },
  { moviesCount: 2, ratingAvg: 7.8, title: "George P. Cosmatos" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Bill Forsyth" },
  { moviesCount: 2, ratingAvg: 6.55, title: "Jon Turteltaub" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Tom Stoppard" },
  { moviesCount: 2, ratingAvg: 7.2, title: "Savage Steve Holland" },
  { moviesCount: 2, ratingAvg: 7.3, title: "Campbell Scott" },
  { moviesCount: 2, ratingAvg: 7.2, title: "Jean-Jacques Beineix" },
  { moviesCount: 2, ratingAvg: 8.3, title: "Godfrey Reggio" },
  { moviesCount: 2, ratingAvg: 7.1, title: "Russell Mulcahy" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Mike Figgis" },
  { moviesCount: 2, ratingAvg: 7.2, title: "Michael Lehmann" },
  { moviesCount: 2, ratingAvg: 7.6, title: "Fred M. Wilcox" },
  { moviesCount: 2, ratingAvg: 7.8, title: "John Hughes" },
  { moviesCount: 2, ratingAvg: 7.2, title: "Peter Cattaneo" },
  { moviesCount: 2, ratingAvg: 7.3, title: "George Armitage" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Steven Zaillian" },
  { moviesCount: 2, ratingAvg: 7.7, title: "Jim Abrahams" },
  { moviesCount: 2, ratingAvg: 7.8, title: "Robert Stevenson" },
  { moviesCount: 2, ratingAvg: 7.7, title: "Mike Newell" },
  { moviesCount: 2, ratingAvg: 7.8, title: "Penny Marshall" },
  { moviesCount: 2, ratingAvg: 7.7, title: "Jean-Jacques Annaud" },
  { moviesCount: 2, ratingAvg: 7.8, title: "Bob Fosse" },
  { moviesCount: 2, ratingAvg: 8.4, title: "Chuck Jones" },
  { moviesCount: 2, ratingAvg: 7.1, title: "David O. Russell" },
  { moviesCount: 2, ratingAvg: 8.4, title: "Marcel CarnÃ©" },
  { moviesCount: 2, ratingAvg: 8.1, title: "Brian Desmond Hurst" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Bill Condon" },
  { moviesCount: 2, ratingAvg: 7.35, title: "Alexander Payne" },
  { moviesCount: 2, ratingAvg: 7.7, title: "Trey Parker" },
  { moviesCount: 2, ratingAvg: 8, title: "Louis Malle" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Kimberly Peirce" },
  { moviesCount: 2, ratingAvg: 7, title: "Peter Lord" },
  { moviesCount: 2, ratingAvg: 7.7, title: "Stephen Daldry" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Lukas Moodysson" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Kenneth Lonergan" },
  { moviesCount: 2, ratingAvg: 7.3, title: "Terry Zwigoff" },
  { moviesCount: 2, ratingAvg: 7.5, title: "Niki Caro" },
  { moviesCount: 2, ratingAvg: 7.4, title: "Zach Braff" },
  { moviesCount: 2, ratingAvg: 8, title: "Jacques Tourneur" },
  { moviesCount: 2, ratingAvg: 7.85, title: "Edgar Wright" },
  { moviesCount: 2, ratingAvg: 8, title: "JosÃ© Padilha" },
  { moviesCount: 2, ratingAvg: 8, title: "Morten Tyldum" },
  { moviesCount: 2, ratingAvg: 8.1, title: "Neeraj Pandey" },
  { moviesCount: 2, ratingAvg: 8.1, title: "Peter Bogdanovich" },
  { moviesCount: 2, ratingAvg: 8.2, title: "Zaza Urushadze" },
  { moviesCount: 2, ratingAvg: 8.4, title: "Thomas Kail" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Jonathan Frakes" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Hettie Macdonald" },
  { moviesCount: 1, ratingAvg: 6.9, title: "Lou Adler" },
  { moviesCount: 1, ratingAvg: 6.9, title: "Tom Hanks" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Bruce Robinson" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Nelson Shin" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Jim Mallon" },
  { moviesCount: 1, ratingAvg: 6.5, title: "Richard Compton" },
  { moviesCount: 1, ratingAvg: 6.8, title: "Stanley Tong" },
  { moviesCount: 1, ratingAvg: 6.7, title: "Douglas McGrath" },
  { moviesCount: 1, ratingAvg: 6.8, title: "Lesli Linka Glatter" },
  { moviesCount: 1, ratingAvg: 7.4, title: "Hal Hartley" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Stephen Herek" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Alex Proyas" },
  { moviesCount: 1, ratingAvg: 6.1, title: "Tommy Chong" },
  { moviesCount: 1, ratingAvg: 5.5, title: "Peter Hewitt" },
  { moviesCount: 1, ratingAvg: 7.5, title: "RÃ©my Belvaux" },
  { moviesCount: 1, ratingAvg: 6.8, title: "Stephen Hopkins" },
  { moviesCount: 1, ratingAvg: 7.2, title: "Jeannot Szwarc" },
  { moviesCount: 1, ratingAvg: 6.7, title: "Rick Moranis" },
  { moviesCount: 1, ratingAvg: 6.8, title: "Renny Harlin" },
  { moviesCount: 1, ratingAvg: 7.9, title: "George A. Romero" },
  { moviesCount: 1, ratingAvg: 8, title: "Alan Parker" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Gillian Armstrong" },
  { moviesCount: 1, ratingAvg: 7.8, title: "Mel Stuart" },
  { moviesCount: 1, ratingAvg: 7.1, title: "Howard Deutch" },
  { moviesCount: 1, ratingAvg: 7.5, title: "Stephan Elliott" },
  { moviesCount: 1, ratingAvg: 7, title: "Roland Emmerich" },
  { moviesCount: 1, ratingAvg: 7.2, title: "Kathryn Bigelow" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Kaige Chen" },
  { moviesCount: 1, ratingAvg: 7, title: "Martha Coolidge" },
  { moviesCount: 1, ratingAvg: 7.1, title: "Antonia Bird" },
  { moviesCount: 1, ratingAvg: 7.4, title: "Jim Sharman" },
  { moviesCount: 1, ratingAvg: 6.9, title: "Amy Heckerling" },
  { moviesCount: 1, ratingAvg: 7.2, title: "Robert Redford" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Scott Hicks" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Wes Craven" },
  { moviesCount: 1, ratingAvg: 7.3, title: "Barry Sonnenfeld" },
  { moviesCount: 1, ratingAvg: 8, title: "Kevin Costner" },
  { moviesCount: 1, ratingAvg: 7.1, title: "Bobby Farrelly" },
  { moviesCount: 1, ratingAvg: 7.5, title: "Gary Ross" },
  { moviesCount: 1, ratingAvg: 7.2, title: "David Mamet" },
  { moviesCount: 1, ratingAvg: 6.5, title: "Eric Darnell" },
  { moviesCount: 1, ratingAvg: 7.8, title: "John Singleton" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Cecil B. DeMille" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Wolfgang Reitherman" },
  { moviesCount: 1, ratingAvg: 7.8, title: "Andrew Niccol" },
  { moviesCount: 1, ratingAvg: 7.5, title: "Martin Brest" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Bernardo Bertolucci" },
  { moviesCount: 1, ratingAvg: 7.6, title: "FranÃ§ois Girard" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Todd Solondz" },
  { moviesCount: 1, ratingAvg: 7.4, title: "Shekhar Kapur" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Luis BuÃ±uel" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Edward Dmytryk" },
  { moviesCount: 1, ratingAvg: 8.4, title: "Bill Melendez" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Preston Sturges" },
  { moviesCount: 1, ratingAvg: 7.4, title: "Steve Box" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Richard Brooks" },
  { moviesCount: 1, ratingAvg: 7.4, title: "Jason Reitman" },
  { moviesCount: 1, ratingAvg: 7.5, title: "Robert Rodriguez" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Werner Herzog" },
  { moviesCount: 1, ratingAvg: 7.8, title: "Joe Wright" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Jean-Pierre Melville" },
  { moviesCount: 1, ratingAvg: 8, title: "Alexander Mackendrick" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Fred C. Newmeyer" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Marc Webb" },
  { moviesCount: 1, ratingAvg: 8, title: "Henry Selick" },
  { moviesCount: 1, ratingAvg: 8, title: "Martin Campbell" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Matthew Vaughn" },
  { moviesCount: 1, ratingAvg: 7.8, title: "Nicolas Winding Refn" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Michel Hazanavicius" },
  { moviesCount: 1, ratingAvg: 7.7, title: "Ben Affleck" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Stephen Chbosky" },
  { moviesCount: 1, ratingAvg: 8.1, title: "YÃ´jirÃ´ Takita" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Farhan Akhtar" },
  { moviesCount: 1, ratingAvg: 7.6, title: "Ryan Coogler" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Rajkumar Santoshi" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Priyadarshan" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Ramesh Sippy" },
  { moviesCount: 1, ratingAvg: 7.8, title: "Gareth Edwards" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Moustapha Akkad" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Vikramaditya Motwane" },
  { moviesCount: 1, ratingAvg: 8, title: "Byron Howard" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Shimit Amin" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Taika Waititi" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Sujoy Ghosh" },
  { moviesCount: 1, ratingAvg: 7.9, title: "Noah Baumbach" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Michael Powell" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Raoul Walsh" },
  { moviesCount: 1, ratingAvg: 8.3, title: "Jeethu Joseph" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Hrishikesh Mukherjee" },
  { moviesCount: 1, ratingAvg: 8.3, title: "Gayatri" },
  { moviesCount: 1, ratingAvg: 8.1, title: "CÃ©line Sciamma" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Oriol Paulo" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Nuri Bilge Ceylan" },
  { moviesCount: 1, ratingAvg: 8.7, title: "Jon Watts" },
  { moviesCount: 1, ratingAvg: 8.3, title: "Florian Zeller" },
  { moviesCount: 1, ratingAvg: 8.4, title: "Satyajit Ray" },
  { moviesCount: 1, ratingAvg: 9.3, title: "T.J. Gnanavel" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Costa-Gavras" },
  { moviesCount: 1, ratingAvg: 8.2, title: "Naoko Yamada" },
  { moviesCount: 1, ratingAvg: 8.1, title: "Hideaki Anno" },
  { moviesCount: 1, ratingAvg: 8.4, title: "Ram Kumar" },
  { moviesCount: 1, ratingAvg: 8.7, title: "Shoojit Sircar" },
];

const ratingMoviesByYearData = [
  { year: 1925, rating: 8.2, label: "The Gold Rush" },
  { year: 1925, rating: 8.2, label: "The Gold Rush" },
  { year: 1927, rating: 8.3, label: "Metropolis" },
  { year: 1927, rating: 8.3, label: "Metropolis" },
  { year: 1931, rating: 8.3, label: "M" },
  { year: 1931, rating: 8.5, label: "City Lights" },
  { year: 1933, rating: 7.8, label: "Duck Soup" },
  { year: 1933, rating: 7.8, label: "Duck Soup" },
  { year: 1936, rating: 8.5, label: "Modern Times" },
  { year: 1936, rating: 8.5, label: "Modern Times" },
  { year: 1937, rating: 7.6, label: "Snow White and the Seven Dwarfs" },
  { year: 1938, rating: 7.9, label: "Bringing Up Baby" },
  { year: 1939, rating: 8.1, label: "Gone with the Wind" },
  { year: 1939, rating: 8.1, label: "Mr. Smith Goes to Washington" },
  { year: 1939, rating: 8.0, label: "The Wizard of Oz" },
  { year: 1939, rating: 8.1, label: "Gone with the Wind" },
  { year: 1939, rating: 8.0, label: "The Wizard of Oz" },
  { year: 1940, rating: 8.4, label: "The Great Dictator" },
  { year: 1940, rating: 8.1, label: "Rebecca" },
  { year: 1940, rating: 7.9, label: "The Philadelphia Story" },
  { year: 1940, rating: 8.4, label: "The Great Dictator" },
  { year: 1940, rating: 7.7, label: "Fantasia" },
  { year: 1940, rating: 7.9, label: "The Philadelphia Story" },
  { year: 1940, rating: 7.7, label: "Fantasia" },
  { year: 1941, rating: 8.3, label: "Citizen Kane" },
  { year: 1941, rating: 8.0, label: "The Maltese Falcon" },
  { year: 1941, rating: 8.3, label: "Citizen Kane" },
  { year: 1941, rating: 8.0, label: "The Maltese Falcon" },
  { year: 1942, rating: 8.5, label: "Casablanca" },
  { year: 1942, rating: 8.5, label: "Casablanca" },
  { year: 1943, rating: 8.0, label: "Arsenic and Old Lace" },
  { year: 1943, rating: 8.0, label: "Arsenic and Old Lace" },
  { year: 1944, rating: 8.3, label: "Double Indemnity" },
  { year: 1946, rating: 7.9, label: "The Big Sleep" },
  { year: 1946, rating: 8.6, label: "It's a Wonderful Life" },
  { year: 1946, rating: 7.9, label: "The Big Sleep" },
  { year: 1946, rating: 8.0, label: "Notorious" },
  { year: 1946, rating: 8.6, label: "It's a Wonderful Life" },
  { year: 1948, rating: 8.2, label: "The Treasure of the Sierra Madre" },
  { year: 1948, rating: 8.2, label: "The Treasure of the Sierra Madre" },
  { year: 1949, rating: 8.1, label: "The Third Man" },
  { year: 1949, rating: 8.1, label: "The Third Man" },
  { year: 1950, rating: 8.4, label: "Sunset Blvd." },
  { year: 1950, rating: 8.2, label: "Rashomon" },
  { year: 1950, rating: 8.2, label: "All About Eve" },
  { year: 1950, rating: 8.2, label: "Rashomon" },
  { year: 1951, rating: 7.8, label: "The African Queen" },
  { year: 1951, rating: 7.7, label: "The Day the Earth Stood Still" },
  { year: 1951, rating: 7.7, label: "The Day the Earth Stood Still" },
  { year: 1951, rating: 7.8, label: "The African Queen" },
  { year: 1952, rating: 7.8, label: "The Quiet Man" },
  { year: 1952, rating: 8.0, label: "High Noon" },
  { year: 1952, rating: 8.0, label: "High Noon" },
  { year: 1952, rating: 7.8, label: "The Quiet Man" },
  { year: 1952, rating: 8.3, label: "Singin' in the Rain" },
  { year: 1952, rating: 8.3, label: "Singin' in the Rain" },
  { year: 1953, rating: 8.0, label: "Roman Holiday" },
  { year: 1953, rating: 8.0, label: "Roman Holiday" },
  { year: 1954, rating: 7.6, label: "Sabrina" },
  { year: 1954, rating: 8.5, label: "Rear Window" },
  { year: 1954, rating: 8.6, label: "Seven Samurai" },
  { year: 1954, rating: 8.2, label: "Dial M for Murder" },
  { year: 1954, rating: 8.1, label: "On the Waterfront" },
  { year: 1954, rating: 8.6, label: "Seven Samurai" },
  { year: 1954, rating: 8.1, label: "On the Waterfront" },
  { year: 1954, rating: 8.5, label: "Rear Window" },
  { year: 1955, rating: 7.7, label: "Rebel Without a Cause" },
  { year: 1956, rating: 7.9, label: "The Searchers" },
  { year: 1956, rating: 7.6, label: "Forbidden Planet" },
  { year: 1956, rating: 7.6, label: "Forbidden Planet" },
  { year: 1957, rating: 8.2, label: "The Seventh Seal" },
  { year: 1957, rating: 9.0, label: "12 Angry Men" },
  { year: 1957, rating: 8.2, label: "The Seventh Seal" },
  { year: 1957, rating: 8.1, label: "The Bridge on the River Kwai" },
  { year: 1957, rating: 8.1, label: "The Bridge on the River Kwai" },
  { year: 1957, rating: 8.4, label: "Paths of Glory" },
  { year: 1957, rating: 9.0, label: "12 Angry Men" },
  { year: 1958, rating: 8.0, label: "Touch of Evil" },
  { year: 1958, rating: 8.3, label: "Vertigo" },
  { year: 1958, rating: 8.0, label: "Touch of Evil" },
  { year: 1958, rating: 8.3, label: "Vertigo" },
  { year: 1959, rating: 8.2, label: "Some Like It Hot" },
  { year: 1959, rating: 8.1, label: "Ben-Hur" },
  { year: 1959, rating: 8.3, label: "North by Northwest" },
  { year: 1959, rating: 8.2, label: "Some Like It Hot" },
  { year: 1959, rating: 8.3, label: "North by Northwest" },
  { year: 1959, rating: 8.1, label: "Ben-Hur" },
  { year: 1960, rating: 7.9, label: "Spartacus" },
  { year: 1960, rating: 8.5, label: "Psycho" },
  { year: 1960, rating: 8.5, label: "Psycho" },
  { year: 1961, rating: 7.6, label: "Breakfast at Tiffany's" },
  { year: 1961, rating: 7.6, label: "Breakfast at Tiffany's" },
  { year: 1961, rating: 7.5, label: "West Side Story" },
  { year: 1962, rating: 7.9, label: "The Manchurian Candidate" },
  { year: 1962, rating: 8.3, label: "Lawrence of Arabia" },
  { year: 1962, rating: 8.2, label: "To Kill a Mockingbird" },
  { year: 1962, rating: 7.9, label: "The Manchurian Candidate" },
  { year: 1962, rating: 8.3, label: "Lawrence of Arabia" },
  { year: 1962, rating: 8.2, label: "To Kill a Mockingbird" },
  { year: 1963, rating: 7.7, label: "The Birds" },
  { year: 1963, rating: 8.0, label: "8½" },
  { year: 1963, rating: 7.9, label: "Charade" },
  { year: 1963, rating: 8.0, label: "8½" },
  { year: 1963, rating: 8.2, label: "The Great Escape" },
  { year: 1963, rating: 8.2, label: "The Great Escape" },
  { year: 1964, rating: 7.7, label: "Goldfinger" },
  { year: 1964, rating: 7.8, label: "My Fair Lady" },
  {
    year: 1964,
    rating: 8.4,
    label:
      "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  },
  {
    year: 1964,
    rating: 8.4,
    label:
      "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  },
  { year: 1964, rating: 7.8, label: "My Fair Lady" },
  { year: 1964, rating: 7.8, label: "Mary Poppins" },
  { year: 1965, rating: 8.0, label: "Doctor Zhivago" },
  { year: 1965, rating: 8.0, label: "The Sound of Music" },
  { year: 1965, rating: 8.0, label: "The Sound of Music" },
  { year: 1966, rating: 8.8, label: "The Good, the Bad and the Ugly" },
  { year: 1966, rating: 8.8, label: "The Good, the Bad and the Ugly" },
  { year: 1967, rating: 8.1, label: "Cool Hand Luke" },
  { year: 1967, rating: 8.1, label: "Cool Hand Luke" },
  { year: 1967, rating: 8.0, label: "The Graduate" },
  { year: 1967, rating: 7.6, label: "The Producers" },
  { year: 1967, rating: 8.0, label: "The Graduate" },
  { year: 1968, rating: 8.3, label: "2001: A Space Odyssey" },
  { year: 1968, rating: 8.5, label: "Once Upon a Time in the West" },
  { year: 1968, rating: 8.3, label: "2001: A Space Odyssey" },
  { year: 1968, rating: 8.5, label: "Once Upon a Time in the West" },
  { year: 1969, rating: 8.0, label: "Butch Cassidy and the Sundance Kid" },
  { year: 1969, rating: 7.9, label: "The Wild Bunch" },
  { year: 1969, rating: 7.9, label: "The Wild Bunch" },
  { year: 1970, rating: 7.9, label: "Patton" },
  { year: 1970, rating: 7.6, label: "Little Big Man" },
  { year: 1970, rating: 7.9, label: "Patton" },
  { year: 1970, rating: 7.4, label: "MASH" },
  { year: 1971, rating: 8.3, label: "A Clockwork Orange" },
  { year: 1971, rating: 7.8, label: "Willy Wonka & the Chocolate Factory" },
  { year: 1971, rating: 7.9, label: "Harold and Maude" },
  { year: 1971, rating: 8.3, label: "A Clockwork Orange" },
  { year: 1971, rating: 7.9, label: "Harold and Maude" },
  { year: 1972, rating: 9.2, label: "The Godfather" },
  { year: 1972, rating: 9.2, label: "The Godfather" },
  { year: 1972, rating: 7.8, label: "Cabaret" },
  { year: 1972, rating: 7.7, label: "Deliverance" },
  { year: 1973, rating: 8.3, label: "The Sting" },
  { year: 1973, rating: 8.0, label: "Papillon" },
  { year: 1973, rating: 8.3, label: "The Sting" },
  { year: 1974, rating: 8.0, label: "Young Frankenstein" },
  { year: 1974, rating: 7.8, label: "The Conversation" },
  { year: 1974, rating: 8.2, label: "Chinatown" },
  { year: 1974, rating: 8.2, label: "Chinatown" },
  { year: 1974, rating: 8.0, label: "Young Frankenstein" },
  { year: 1974, rating: 9.0, label: "The Godfather: Part II" },
  { year: 1974, rating: 9.0, label: "The Godfather: Part II" },
  { year: 1975, rating: 7.8, label: "The Man Who Would Be King" },
  { year: 1975, rating: 8.0, label: "Jaws" },
  { year: 1975, rating: 8.2, label: "Monty Python and the Holy Grail" },
  { year: 1975, rating: 7.4, label: "The Rocky Horror Picture Show" },
  { year: 1975, rating: 8.0, label: "Dog Day Afternoon" },
  { year: 1975, rating: 8.7, label: "One Flew Over the Cuckoo's Nest" },
  { year: 1975, rating: 7.8, label: "The Man Who Would Be King" },
  { year: 1975, rating: 8.2, label: "Monty Python and the Holy Grail" },
  { year: 1975, rating: 8.7, label: "One Flew Over the Cuckoo's Nest" },
  { year: 1976, rating: 8.2, label: "Taxi Driver" },
  { year: 1976, rating: 8.0, label: "All the President's Men" },
  { year: 1976, rating: 8.2, label: "Taxi Driver" },
  { year: 1977, rating: 8.6, label: "Star Wars: Episode IV - A New Hope" },
  { year: 1977, rating: 8.0, label: "Annie Hall" },
  { year: 1977, rating: 8.0, label: "Annie Hall" },
  { year: 1977, rating: 8.6, label: "Star Wars: Episode IV - A New Hope" },
  { year: 1978, rating: 8.1, label: "The Deer Hunter" },
  { year: 1978, rating: 8.1, label: "The Deer Hunter" },
  { year: 1978, rating: 6.9, label: "Up in Smoke" },
  { year: 1978, rating: 7.5, label: "National Lampoon's Animal House" },
  { year: 1978, rating: 7.9, label: "Dawn of the Dead" },
  { year: 1979, rating: 7.9, label: "Manhattan" },
  { year: 1979, rating: 8.1, label: "Life of Brian" },
  { year: 1979, rating: 8.0, label: "Being There" },
  { year: 1979, rating: 8.4, label: "Apocalypse Now" },
  { year: 1979, rating: 8.1, label: "Stalker" },
  { year: 1979, rating: 7.9, label: "Manhattan" },
  { year: 1979, rating: 8.4, label: "Apocalypse Now" },
  { year: 1979, rating: 8.0, label: "Being There" },
  { year: 1979, rating: 8.1, label: "Life of Brian" },
  { year: 1979, rating: 8.4, label: "Alien" },
  { year: 1979, rating: 8.4, label: "Alien" },
  { year: 1980, rating: 8.4, label: "The Shining" },
  {
    year: 1980,
    rating: 8.7,
    label: "Star Wars: Episode V - The Empire Strikes Back",
  },
  { year: 1980, rating: 7.9, label: "The Blues Brothers" },
  { year: 1980, rating: 8.2, label: "Raging Bull" },
  { year: 1980, rating: 8.4, label: "The Shining" },
  { year: 1980, rating: 7.2, label: "Somewhere in Time" },
  { year: 1980, rating: 8.2, label: "Raging Bull" },
  { year: 1980, rating: 6.1, label: "Cheech and Chong's Next Movie" },
  { year: 1980, rating: 7.7, label: "Airplane!" },
  { year: 1980, rating: 8.1, label: "The Elephant Man" },
  { year: 1980, rating: 7.9, label: "The Blues Brothers" },
  {
    year: 1980,
    rating: 8.7,
    label: "Star Wars: Episode V - The Empire Strikes Back",
  },
  { year: 1981, rating: 7.2, label: "Diva" },
  { year: 1981, rating: 7.4, label: "Gallipoli" },
  {
    year: 1981,
    rating: 8.4,
    label: "Indiana Jones and the Raiders of the Lost Ark",
  },
  { year: 1981, rating: 8.3, label: "Das Boot" },
  { year: 1981, rating: 8.3, label: "Das Boot" },
  {
    year: 1981,
    rating: 8.4,
    label: "Indiana Jones and the Raiders of the Lost Ark",
  },
  { year: 1981, rating: 7.2, label: "Diva" },
  { year: 1982, rating: 8.3, label: "Koyaanisqatsi" },
  { year: 1982, rating: 8.1, label: "Blade Runner" },
  { year: 1982, rating: 8.3, label: "Koyaanisqatsi" },
  { year: 1982, rating: 8.0, label: "Gandhi" },
  { year: 1982, rating: 8.1, label: "Blade Runner" },
  { year: 1982, rating: 8.0, label: "Gandhi" },
  { year: 1982, rating: 8.0, label: "Pink Floyd: The Wall" },
  { year: 1983, rating: 7.4, label: "Local Hero" },
  {
    year: 1983,
    rating: 8.3,
    label: "Star Wars: Episode VI - Return of the Jedi",
  },
  { year: 1983, rating: 7.8, label: "The Right Stuff" },
  { year: 1983, rating: 7.9, label: "A Christmas Story" },
  { year: 1983, rating: 7.8, label: "The Right Stuff" },
  {
    year: 1983,
    rating: 8.3,
    label: "Star Wars: Episode VI - Return of the Jedi",
  },
  { year: 1983, rating: 7.9, label: "A Christmas Story" },
  { year: 1983, rating: 6.7, label: "Strange Brew" },
  { year: 1983, rating: 7.4, label: "Local Hero" },
  { year: 1984, rating: 8.3, label: "Amadeus" },
  { year: 1984, rating: 8.0, label: "The Terminator" },
  { year: 1984, rating: 7.9, label: "This Is Spinal Tap" },
  { year: 1984, rating: 7.8, label: "The Killing Fields" },
  { year: 1984, rating: 7.6, label: "Blood Simple" },
  { year: 1984, rating: 8.3, label: "Amadeus" },
  { year: 1984, rating: 8.1, label: "Paris, Texas" },
  { year: 1984, rating: 8.1, label: "Paris, Texas" },
  { year: 1984, rating: 8.3, label: "Once Upon a Time in America" },
  { year: 1984, rating: 7.9, label: "This Is Spinal Tap" },
  { year: 1984, rating: 8.3, label: "Once Upon a Time in America" },
  { year: 1984, rating: 7.8, label: "The Killing Fields" },
  { year: 1984, rating: 8.0, label: "The Terminator" },
  { year: 1985, rating: 7.3, label: "A Room with a View" },
  { year: 1985, rating: 8.2, label: "Ran" },
  { year: 1985, rating: 7.8, label: "The Breakfast Club" },
  { year: 1985, rating: 7.2, label: "Better Off Dead..." },
  { year: 1985, rating: 7.3, label: "A Room with a View" },
  { year: 1985, rating: 7.6, label: "My Life as a Dog" },
  { year: 1985, rating: 7.9, label: "Brazil" },
  { year: 1985, rating: 7.0, label: "Real Genius" },
  { year: 1985, rating: 7.4, label: "Witness" },
  { year: 1985, rating: 8.5, label: "Back to the Future" },
  { year: 1985, rating: 7.2, label: "Better Off Dead..." },
  { year: 1985, rating: 8.2, label: "Ran" },
  { year: 1985, rating: 7.9, label: "Brazil" },
  { year: 1985, rating: 7.6, label: "My Life as a Dog" },
  { year: 1985, rating: 8.5, label: "Back to the Future" },
  { year: 1986, rating: 8.1, label: "Stand by Me" },
  { year: 1986, rating: 8.1, label: "Platoon" },
  { year: 1986, rating: 8.3, label: "Aliens" },
  { year: 1986, rating: 7.3, label: "The Transformers: The Movie" },
  { year: 1986, rating: 7.7, label: "The Name of the Rose" },
  { year: 1986, rating: 8.0, label: "Jean de Florette" },
  { year: 1986, rating: 8.0, label: "Jean de Florette" },
  { year: 1986, rating: 7.7, label: "Blue Velvet" },
  { year: 1986, rating: 7.7, label: "Down by Law" },
  { year: 1986, rating: 7.1, label: "Highlander" },
  { year: 1986, rating: 8.0, label: "Manon of the Spring" },
  { year: 1986, rating: 8.1, label: "Stand by Me" },
  { year: 1986, rating: 7.1, label: "Highlander" },
  { year: 1986, rating: 8.3, label: "Aliens" },
  { year: 1987, rating: 7.7, label: "Evil Dead II" },
  { year: 1987, rating: 7.9, label: "The Untouchables" },
  { year: 1987, rating: 8.1, label: "The Princess Bride" },
  { year: 1987, rating: 7.3, label: "Raising Arizona" },
  { year: 1987, rating: 8.0, label: "Wings of Desire" },
  { year: 1987, rating: 7.7, label: "Evil Dead II" },
  { year: 1987, rating: 7.6, label: "Withnail & I" },
  { year: 1987, rating: 8.1, label: "The Princess Bride" },
  { year: 1987, rating: 6.5, label: "Bad Taste" },
  { year: 1987, rating: 8.0, label: "Wings of Desire" },
  { year: 1987, rating: 8.3, label: "Full Metal Jacket" },
  { year: 1987, rating: 8.3, label: "Full Metal Jacket" },
  { year: 1987, rating: 7.1, label: "Some Kind of Wonderful" },
  { year: 1988, rating: 8.0, label: "Rain Man" },
  { year: 1988, rating: 7.3, label: "The Unbearable Lightness of Being" },
  { year: 1988, rating: 7.2, label: "Heathers" },
  { year: 1988, rating: 7.2, label: "Heathers" },
  { year: 1988, rating: 8.2, label: "Die Hard" },
  { year: 1988, rating: 7.6, label: "The Big Blue" },
  { year: 1988, rating: 7.5, label: "A Fish Called Wanda" },
  { year: 1988, rating: 7.6, label: "The Big Blue" },
  { year: 1988, rating: 7.6, label: "Dangerous Liaisons" },
  { year: 1988, rating: 8.0, label: "Akira" },
  { year: 1988, rating: 8.5, label: "Cinema Paradiso" },
  { year: 1988, rating: 8.0, label: "Akira" },
  { year: 1988, rating: 8.2, label: "Die Hard" },
  { year: 1988, rating: 8.5, label: "Cinema Paradiso" },
  { year: 1989, rating: 7.6, label: "When Harry Met Sally..." },
  { year: 1989, rating: 7.8, label: "A Grand Day Out" },
  { year: 1989, rating: 7.9, label: "Crimes and Misdemeanors" },
  { year: 1989, rating: 7.5, label: "Henry V" },
  { year: 1989, rating: 7.8, label: "Glory" },
  { year: 1989, rating: 7.5, label: "Henry V" },
  { year: 1989, rating: 8.2, label: "Indiana Jones and the Last Crusade" },
  { year: 1989, rating: 7.8, label: "A Grand Day Out" },
  { year: 1989, rating: 7.8, label: "Glory" },
  { year: 1989, rating: 7.5, label: "Field of Dreams" },
  { year: 1989, rating: 7.5, label: "Field of Dreams" },
  { year: 1989, rating: 8.1, label: "Dead Poets Society" },
  { year: 1989, rating: 8.2, label: "Indiana Jones and the Last Crusade" },
  { year: 1989, rating: 7.8, label: "The Killer" },
  { year: 1989, rating: 8.1, label: "Dead Poets Society" },
  { year: 1989, rating: 7.8, label: "The Killer" },
  { year: 1990, rating: 8.0, label: "Dances with Wolves" },
  { year: 1990, rating: 7.3, label: "Nikita" },
  { year: 1990, rating: 7.4, label: "Rosencrantz & Guildenstern Are Dead" },
  { year: 1990, rating: 7.8, label: "Awakenings" },
  { year: 1990, rating: 7.4, label: "Trust" },
  { year: 1990, rating: 7.2, label: "Pump Up the Volume" },
  { year: 1990, rating: 7.7, label: "Miller's Crossing" },
  { year: 1990, rating: 7.5, label: "Cyrano de Bergerac" },
  { year: 1990, rating: 7.4, label: "Rosencrantz & Guildenstern Are Dead" },
  { year: 1990, rating: 7.5, label: "Cyrano de Bergerac" },
  { year: 1990, rating: 8.7, label: "Goodfellas" },
  { year: 1990, rating: 8.7, label: "Goodfellas" },
  { year: 1990, rating: 7.7, label: "Miller's Crossing" },
  { year: 1990, rating: 7.6, label: "The Hunt for Red October" },
  { year: 1990, rating: 7.3, label: "Nikita" },
  { year: 1991, rating: 7.8, label: "The Double Life of Véronique" },
  { year: 1991, rating: 8.6, label: "The Silence of the Lambs" },
  { year: 1991, rating: 7.7, label: "Fried Green Tomatoes" },
  { year: 1991, rating: 8.5, label: "Terminator 2: Judgment Day" },
  { year: 1991, rating: 7.7, label: "Night on Earth" },
  { year: 1991, rating: 8.0, label: "Beauty and the Beast" },
  { year: 1991, rating: 8.5, label: "Terminator 2: Judgment Day" },
  { year: 1991, rating: 7.7, label: "Night on Earth" },
  { year: 1991, rating: 7.8, label: "The Double Life of Véronique" },
  { year: 1991, rating: 8.0, label: "Beauty and the Beast" },
  { year: 1991, rating: 7.6, label: "Delicatessen" },
  { year: 1991, rating: 8.6, label: "The Silence of the Lambs" },
  { year: 1991, rating: 7.7, label: "Fried Green Tomatoes" },
  { year: 1991, rating: 6.8, label: "Until the End of the World" },
  { year: 1991, rating: 8.1, label: "Raise the Red Lantern" },
  { year: 1991, rating: 7.6, label: "Delicatessen" },
  { year: 1992, rating: 8.2, label: "Unforgiven" },
  { year: 1992, rating: 8.0, label: "Aladdin" },
  { year: 1992, rating: 7.8, label: "Hard Boiled" },
  { year: 1992, rating: 8.3, label: "Reservoir Dogs" },
  { year: 1992, rating: 7.5, label: "Braindead" },
  { year: 1992, rating: 7.2, label: "A River Runs Through It" },
  { year: 1992, rating: 8.2, label: "Unforgiven" },
  { year: 1992, rating: 7.5, label: "Braindead" },
  { year: 1992, rating: 7.8, label: "Hard Boiled" },
  { year: 1992, rating: 7.7, label: "A Few Good Men" },
  { year: 1992, rating: 7.5, label: "Man Bites Dog" },
  { year: 1992, rating: 7.5, label: "The Player" },
  { year: 1992, rating: 8.3, label: "Reservoir Dogs" },
  { year: 1992, rating: 7.2, label: "Strictly Ballroom" },
  { year: 1992, rating: 8.0, label: "Aladdin" },
  { year: 1992, rating: 7.5, label: "Army of Darkness" },
  { year: 1993, rating: 7.8, label: "Tombstone" },
  { year: 1993, rating: 7.8, label: "Tombstone" },
  { year: 1993, rating: 7.9, label: "Three Colors: Blue" },
  { year: 1993, rating: 8.0, label: "Groundhog Day" },
  { year: 1993, rating: 8.1, label: "In the Name of the Father" },
  { year: 1993, rating: 7.3, label: "Shadowlands" },
  { year: 1993, rating: 7.8, label: "The Remains of the Day" },
  { year: 1993, rating: 7.3, label: "Shadowlands" },
  { year: 1993, rating: 8.3, label: "The Wrong Trousers" },
  { year: 1993, rating: 7.9, label: "True Romance" },
  { year: 1993, rating: 8.1, label: "Farewell My Concubine" },
  { year: 1993, rating: 8.1, label: "In the Name of the Father" },
  { year: 1993, rating: 7.8, label: "The Remains of the Day" },
  { year: 1993, rating: 7.9, label: "Three Colors: Blue" },
  { year: 1993, rating: 7.3, label: "Much Ado About Nothing" },
  { year: 1993, rating: 7.9, label: "True Romance" },
  { year: 1993, rating: 8.9, label: "Schindler's List" },
  { year: 1993, rating: 7.6, label: "Dazed and Confused" },
  { year: 1993, rating: 7.8, label: "The Fugitive" },
  { year: 1993, rating: 7.7, label: "Short Cuts" },
  { year: 1993, rating: 7.8, label: "Naked" },
  { year: 1993, rating: 6.5, label: " Babylon 5" },
  { year: 1993, rating: 8.9, label: "Schindler's List" },
  { year: 1993, rating: 8.3, label: "The Wrong Trousers" },
  { year: 1993, rating: 7.4, label: "Searching for Bobby Fischer" },
  { year: 1993, rating: 7.8, label: "Naked" },
  { year: 1993, rating: 7.8, label: "The Fugitive" },
  { year: 1993, rating: 8.0, label: "Groundhog Day" },
  { year: 1993, rating: 7.7, label: "What's Eating Gilbert Grape" },
  { year: 1993, rating: 7.3, label: "Much Ado About Nothing" },
  { year: 1994, rating: 8.5, label: "Léon: The Professional" },
  { year: 1994, rating: 8.8, label: "Forrest Gump" },
  { year: 1994, rating: 7.3, label: "Little Women" },
  { year: 1994, rating: 7.3, label: "Shallow Grave" },
  { year: 1994, rating: 8.8, label: "Forrest Gump" },
  { year: 1994, rating: 7.6, label: "The Crow" },
  { year: 1994, rating: 7.1, label: "Exotica" },
  { year: 1994, rating: 7.3, label: "Heavenly Creatures" },
  { year: 1994, rating: 8.1, label: "Three Colors: Red" },
  { year: 1994, rating: 9.3, label: "The Shawshank Redemption" },
  { year: 1994, rating: 7.7, label: "Clerks" },
  {
    year: 1994,
    rating: 7.5,
    label: "The Adventures of Priscilla, Queen of the Desert",
  },
  { year: 1994, rating: 7.3, label: "Heavenly Creatures" },
  { year: 1994, rating: 7.7, label: "The Postman" },
  { year: 1994, rating: 7.9, label: "Once Were Warriors" },
  { year: 1994, rating: 8.5, label: "Léon: The Professional" },
  { year: 1994, rating: 8.9, label: "Pulp Fiction" },
  { year: 1994, rating: 8.9, label: "Pulp Fiction" },
  { year: 1994, rating: 8.1, label: "Three Colors: Red" },
  { year: 1994, rating: 7.9, label: "Once Were Warriors" },
  { year: 1994, rating: 8.5, label: "The Lion King" },
  { year: 1994, rating: 8.5, label: "The Lion King" },
  { year: 1994, rating: 7.1, label: "Priest" },
  { year: 1994, rating: 7.7, label: "The Postman" },
  { year: 1994, rating: 7.3, label: "Shallow Grave" },
  { year: 1994, rating: 7.7, label: "Clerks" },
  { year: 1994, rating: 7.8, label: "Ed Wood" },
  { year: 1994, rating: 9.3, label: "The Shawshank Redemption" },
  { year: 1994, rating: 7.6, label: "Three Colors: White" },
  { year: 1995, rating: 8.1, label: "A Close Shave" },
  { year: 1995, rating: 8.3, label: "Toy Story" },
  { year: 1995, rating: 8.5, label: "The Usual Suspects" },
  { year: 1995, rating: 8.3, label: "Braveheart" },
  { year: 1995, rating: 7.5, label: "Leaving Las Vegas" },
  { year: 1995, rating: 7.1, label: "Mallrats" },
  { year: 1995, rating: 8.2, label: "Heat" },
  { year: 1995, rating: 7.5, label: "Dead Man Walking" },
  { year: 1995, rating: 7.3, label: "Mr. Holland's Opus" },
  { year: 1995, rating: 6.7, label: "While You Were Sleeping" },
  { year: 1995, rating: 8.6, label: "Se7en" },
  { year: 1995, rating: 8.1, label: "Underground" },
  { year: 1995, rating: 7.7, label: "Sense and Sensibility" },
  { year: 1995, rating: 7.6, label: "Apollo 13" },
  { year: 1995, rating: 6.8, label: "Now and Then" },
  { year: 1995, rating: 8.2, label: "Heat" },
  { year: 1995, rating: 8.1, label: "A Close Shave" },
  { year: 1995, rating: 8.0, label: "12 Monkeys" },
  { year: 1995, rating: 8.3, label: "Toy Story" },
  { year: 1995, rating: 7.6, label: "Apollo 13" },
  { year: 1995, rating: 6.9, label: "Clueless" },
  { year: 1995, rating: 7.2, label: "Strange Days" },
  { year: 1995, rating: 6.7, label: "Empire Records" },
  { year: 1995, rating: 6.8, label: "Babe" },
  { year: 1995, rating: 7.4, label: "Smoke" },
  { year: 1995, rating: 6.8, label: "Babe" },
  { year: 1995, rating: 7.6, label: "Dead Man" },
  { year: 1995, rating: 8.3, label: "Braveheart" },
  { year: 1995, rating: 7.7, label: "Sense and Sensibility" },
  { year: 1995, rating: 6.8, label: "Rumble in the Bronx" },
  { year: 1995, rating: 7.5, label: "The City of Lost Children" },
  { year: 1995, rating: 8.5, label: "The Usual Suspects" },
  { year: 1995, rating: 7.5, label: "Dead Man Walking" },
  { year: 1995, rating: 7.5, label: "The City of Lost Children" },
  { year: 1995, rating: 7.4, label: "Smoke" },
  { year: 1995, rating: 8.6, label: "Se7en" },
  { year: 1995, rating: 8.1, label: "Before Sunrise" },
  { year: 1995, rating: 5.5, label: "Tom and Huck" },
  { year: 1995, rating: 7.5, label: "Leaving Las Vegas" },
  { year: 1995, rating: 8.0, label: "12 Monkeys" },
  { year: 1996, rating: 7.6, label: "Star Trek: First Contact" },
  { year: 1996, rating: 6.6, label: "Courage Under Fire" },
  { year: 1996, rating: 7.5, label: "A Time to Kill" },
  { year: 1996, rating: 7.3, label: "Big Night" },
  { year: 1996, rating: 7.6, label: "Sleepers" },
  { year: 1996, rating: 7.0, label: "The Hunchback of Notre Dame" },
  { year: 1996, rating: 7.0, label: "Independence Day" },
  { year: 1996, rating: 7.4, label: "The Rock" },
  { year: 1996, rating: 7.3, label: "Bound" },
  { year: 1996, rating: 8.1, label: "Trainspotting" },
  { year: 1996, rating: 6.8, label: "The Long Kiss Goodnight" },
  { year: 1996, rating: 6.8, label: "The Ghost and the Darkness" },
  { year: 1996, rating: 7.3, label: "Big Night" },
  { year: 1996, rating: 6.4, label: "Phenomenon" },
  { year: 1996, rating: 7.3, label: "Jerry Maguire" },
  { year: 1996, rating: 7.4, label: "The English Patient" },
  { year: 1996, rating: 7.3, label: "The People vs. Larry Flynt" },
  { year: 1996, rating: 6.7, label: "Ransom" },
  { year: 1996, rating: 7.3, label: "Mystery Science Theater 3000: The Movie" },
  { year: 1996, rating: 6.7, label: "Romeo + Juliet" },
  { year: 1996, rating: 6.9, label: "That Thing You Do!" },
  { year: 1996, rating: 7.2, label: "Swingers" },
  { year: 1996, rating: 7.7, label: "Hamlet" },
  { year: 1996, rating: 7.3, label: "Scream" },
  { year: 1996, rating: 8.1, label: "Trainspotting" },
  { year: 1996, rating: 7.7, label: "Shine" },
  { year: 1996, rating: 6.7, label: "Emma" },
  { year: 1996, rating: 7.3, label: "Bound" },
  { year: 1996, rating: 7.5, label: "A Time to Kill" },
  { year: 1996, rating: 7.8, label: "Breaking the Waves" },
  { year: 1996, rating: 7.4, label: "The Rock" },
  { year: 1996, rating: 7.4, label: "Lone Star" },
  { year: 1996, rating: 8.0, label: "Secrets & Lies" },
  { year: 1996, rating: 8.0, label: "Secrets & Lies" },
  { year: 1996, rating: 7.4, label: "Lone Star" },
  { year: 1996, rating: 8.0, label: "Sling Blade" },
  { year: 1996, rating: 7.6, label: "Beautiful Thing" },
  { year: 1996, rating: 7.4, label: "The English Patient" },
  { year: 1996, rating: 8.1, label: "Fargo" },
  { year: 1996, rating: 8.1, label: "Fargo" },
  { year: 1997, rating: 7.7, label: "The Fifth Element" },
  { year: 1997, rating: 7.2, label: "Face/Off" },
  { year: 1997, rating: 7.7, label: "The Game" },
  { year: 1997, rating: 8.2, label: "L.A. Confidential" },
  { year: 1997, rating: 7.2, label: "Chasing Amy" },
  { year: 1997, rating: 7.7, label: "Donnie Brasco" },
  { year: 1997, rating: 7.3, label: "Men in Black" },
  { year: 1997, rating: 7.5, label: "Contact" },
  { year: 1997, rating: 7.8, label: "Titanic" },
  { year: 1997, rating: 7.3, label: "Grosse Pointe Blank" },
  { year: 1997, rating: 7.2, label: "The Full Monty" },
];

// Rating vs gross
const initRatingGrossChart = () => {
  const ctx = document.getElementById("ratingGrossMovieChart").getContext("2d");
  new Chart(ctx, {
    type: "scatter",
    data: {
      datasets: [
        {
          label: "Movies (Top ranking)",
          data: ratingGrossMovieData,
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          borderColor: "rgba(54, 162, 235, 1)",
          pointRadius: 6,
          pointHoverRadius: 8,
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      parsing: {
        xAxisKey: "rating",
        yAxisKey: "gross",
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (context) => {
              let point = context.raw;
              return `${point.title},: Rating ${point.rating}, $${point.gross},`;
            },
          },
        },
      },
      scales: {
        x: { title: { display: true, text: "Rating IMDB" }, min: 70, max: 100 },
        y: { title: { display: true, text: "Gross ($)" }, beginAtZero: true },
      },
    },
  });
};

// Rating vs runtime
const initAvgRatingRuntimeMoviesChart = () => {
  const trendlineData = calculateAvgRatingRuntimeMoviesTrendline(averageRatingRuntimeMovieData);
  const ctx = document
    .getElementById("averageRatingRuntimeMovieChart")
    .getContext("2d");
  new Chart(ctx, {
    type: "scatter",
    data: {
      datasets: [
        {
          label: "Movies",
          data: averageRatingRuntimeMovieData,
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          borderColor: "rgba(54, 162, 235, 1)",
          pointRadius: 6,
          pointHoverRadius: 8,
        },
        {
          label: "Trend",
          data: trendlineData,
          parsing: false,
          type: "line",
          borderColor: "rgba(255, 99, 132, 1)",
          borderWidth: 2,
          pointRadius: 0, //Without points in line
          fill: false,
          tension: 0, //Straight line
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      parsing: {
        xAxisKey: "runTime",
        yAxisKey: "averageRating",
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (context) => {
              if (context.dataset.type === "line") return "Trend";
              let point = context.raw;
              return `AVG rating: ${point.averageRating}, Runtime: ${point.runTime} min`;
            },
          },
        },
      },
      scales: {
        x: { title: { display: true, text: "Runtime (min)" } },
        y: { title: { display: true, text: "AVG Rating" }, max: 10 },
      },
    },
  });
};

// Director's avg rating
const initDirectorAvgRatingChart = () => {
  const ctx = document
    .getElementById("directorsAvgRatingChart")
    .getContext("2d");
  new Chart(ctx, {
    type: "scatter",
    data: {
      datasets: [
        {
          label: "Directors",
          data: directorsAvgRatingData,
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          borderColor: "rgba(54, 162, 235, 1)",
          pointRadius: 6,
          pointHoverRadius: 8,
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      parsing: {
        xAxisKey: "moviesCount",
        yAxisKey: "ratingAvg",
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (context) => {
              let point = context.raw;
              return `${point.title}: Movies count: ${point.moviesCount}, Rating AVG: ${point.ratingAvg}`;
            },
          },
        },
      },
      scales: {
        x: { title: { display: true, text: "Movies count" } },
        y: { title: { display: true, text: "Rating AVG" } },
      },
    },
  });
};

// Rating movies by year
const initRatingMoviesByYearChart = () => {
  const trendlineData = calculateRatingMoviesByYearTrendline(ratingMoviesByYearData);
  const ctx = document
    .getElementById("ratingMoviesByYearChart")
    .getContext("2d");
  new Chart(ctx, {
    type: "scatter",
    data: {
      datasets: [
        {
          label: "Movies",
          data: ratingMoviesByYearData,
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          pointRadius: 4,
        },
        {
          label: "Trend",
          data: trendlineData,
          type: "line",
          borderColor: "rgba(255, 99, 132, 1)",
          borderWidth: 2,
          pointRadius: 0, //Without points in line
          fill: false,
          tension: 0, //Straight line
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      parsing: {
        xAxisKey: "year",
        yAxisKey: "rating",
      },
      scales: {
        x: {
          type: "linear",
          position: "bottom",
          title: { display: true, text: "Year" },
        },
        y: { title: { display: true, text: "Rating (IMDb)" } },
      },
      plugins: {
        tooltip: {
          callbacks: {
            label: (context) => {
              if (context.dataset.type === "line") return "Trend";
              const point = context.raw;
              return `${point.label} (${point.year}): ${point.rating}`;
            },
          },
        },
      },
    },
  });
};

//Calculate AvgRatingRuntimeMovies Trendline
const calculateAvgRatingRuntimeMoviesTrendline = (data) => {
  let n = data.length;
  let sumX = 0,
    sumY = 0,
    sumXY = 0,
    sumXX = 0;

  data.forEach((p) => {
    const { runTime, averageRating } = p;
    sumX += runTime;
    sumY += averageRating;
    sumXY += runTime * averageRating;
    sumXX += runTime * runTime;
  });

  const slope = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);
  const intercept = (sumY - slope * sumX) / n;

  //Calculate initial point (min year) y final (max year) to draw the line
  const minRunTime = Math.min(...data.map((d) => d.runTime));
  const maxRunTime = Math.max(...data.map((d) => d.runTime));

  return [
    { x: minRunTime, y: slope * minRunTime + intercept },
    { x: maxRunTime, y: slope * maxRunTime + intercept },
  ];
};

//Calculate RatingMoviesByYear Trendline
const calculateRatingMoviesByYearTrendline = (data) => {
  let n = data.length;
  let sumX = 0,
    sumY = 0,
    sumXY = 0,
    sumXX = 0;

  data.forEach((p) => {
    sumX += p.year;
    sumY += p.rating;
    sumXY += p.year * p.rating;
    sumXX += p.year * p.year;
  });

  const slope = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);
  const intercept = (sumY - slope * sumX) / n;

  //Calculate initial point (min year) y final (max year) to draw the line
  const minYear = Math.min(...data.map((d) => d.year));
  const maxYear = Math.max(...data.map((d) => d.year));

  return [
    { year: minYear, rating: slope * minYear + intercept },
    { year: maxYear, rating: slope * maxYear + intercept },
  ];
};

document.addEventListener("DOMContentLoaded", () => {
  initRatingGrossChart();
  initAvgRatingRuntimeMoviesChart();
  initDirectorAvgRatingChart();
  initRatingMoviesByYearChart();
});
